//Version

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: modules/inventory/inventoryPb/inventoryPb.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryGrpcService_IsAvailableToSell_FullMethodName = "/inventorypb.InventoryGrpcService/IsAvailableToSell"
)

// InventoryGrpcServiceClient is the client API for InventoryGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Methods
type InventoryGrpcServiceClient interface {
	IsAvailableToSell(ctx context.Context, in *IsAvailableToSellReq, opts ...grpc.CallOption) (*IsAvailableToSellRes, error)
}

type inventoryGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryGrpcServiceClient(cc grpc.ClientConnInterface) InventoryGrpcServiceClient {
	return &inventoryGrpcServiceClient{cc}
}

func (c *inventoryGrpcServiceClient) IsAvailableToSell(ctx context.Context, in *IsAvailableToSellReq, opts ...grpc.CallOption) (*IsAvailableToSellRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAvailableToSellRes)
	err := c.cc.Invoke(ctx, InventoryGrpcService_IsAvailableToSell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryGrpcServiceServer is the server API for InventoryGrpcService service.
// All implementations must embed UnimplementedInventoryGrpcServiceServer
// for forward compatibility.
//
// Methods
type InventoryGrpcServiceServer interface {
	IsAvailableToSell(context.Context, *IsAvailableToSellReq) (*IsAvailableToSellRes, error)
	mustEmbedUnimplementedInventoryGrpcServiceServer()
}

// UnimplementedInventoryGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryGrpcServiceServer struct{}

func (UnimplementedInventoryGrpcServiceServer) IsAvailableToSell(context.Context, *IsAvailableToSellReq) (*IsAvailableToSellRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAvailableToSell not implemented")
}
func (UnimplementedInventoryGrpcServiceServer) mustEmbedUnimplementedInventoryGrpcServiceServer() {}
func (UnimplementedInventoryGrpcServiceServer) testEmbeddedByValue()                              {}

// UnsafeInventoryGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryGrpcServiceServer will
// result in compilation errors.
type UnsafeInventoryGrpcServiceServer interface {
	mustEmbedUnimplementedInventoryGrpcServiceServer()
}

func RegisterInventoryGrpcServiceServer(s grpc.ServiceRegistrar, srv InventoryGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedInventoryGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryGrpcService_ServiceDesc, srv)
}

func _InventoryGrpcService_IsAvailableToSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAvailableToSellReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryGrpcServiceServer).IsAvailableToSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryGrpcService_IsAvailableToSell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryGrpcServiceServer).IsAvailableToSell(ctx, req.(*IsAvailableToSellReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryGrpcService_ServiceDesc is the grpc.ServiceDesc for InventoryGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventorypb.InventoryGrpcService",
	HandlerType: (*InventoryGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAvailableToSell",
			Handler:    _InventoryGrpcService_IsAvailableToSell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/inventory/inventoryPb/inventoryPb.proto",
}
