//Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: modules/inventory/inventoryPb/inventoryPb.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structures
type IsAvailableToSellReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAvailableToSellReq) Reset() {
	*x = IsAvailableToSellReq{}
	mi := &file_modules_inventory_inventoryPb_inventoryPb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAvailableToSellReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAvailableToSellReq) ProtoMessage() {}

func (x *IsAvailableToSellReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_inventoryPb_inventoryPb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAvailableToSellReq.ProtoReflect.Descriptor instead.
func (*IsAvailableToSellReq) Descriptor() ([]byte, []int) {
	return file_modules_inventory_inventoryPb_inventoryPb_proto_rawDescGZIP(), []int{0}
}

func (x *IsAvailableToSellReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *IsAvailableToSellReq) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type IsAvailableToSellRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=isAvailable,proto3" json:"isAvailable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAvailableToSellRes) Reset() {
	*x = IsAvailableToSellRes{}
	mi := &file_modules_inventory_inventoryPb_inventoryPb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAvailableToSellRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAvailableToSellRes) ProtoMessage() {}

func (x *IsAvailableToSellRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_inventoryPb_inventoryPb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAvailableToSellRes.ProtoReflect.Descriptor instead.
func (*IsAvailableToSellRes) Descriptor() ([]byte, []int) {
	return file_modules_inventory_inventoryPb_inventoryPb_proto_rawDescGZIP(), []int{1}
}

func (x *IsAvailableToSellRes) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_modules_inventory_inventoryPb_inventoryPb_proto protoreflect.FileDescriptor

const file_modules_inventory_inventoryPb_inventoryPb_proto_rawDesc = "" +
	"\n" +
	"/modules/inventory/inventoryPb/inventoryPb.proto\x12\vinventorypb\"J\n" +
	"\x14IsAvailableToSellReq\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06itemId\x18\x02 \x01(\tR\x06itemId\"8\n" +
	"\x14IsAvailableToSellRes\x12 \n" +
	"\visAvailable\x18\x01 \x01(\bR\visAvailable2s\n" +
	"\x14InventoryGrpcService\x12[\n" +
	"\x11IsAvailableToSell\x12!.inventorypb.IsAvailableToSellReq\x1a!.inventorypb.IsAvailableToSellRes\"\x00BAZ?github.com/watcharaphong99/InwzaShop/modules/auth/authPb;authpbb\x06proto3"

var (
	file_modules_inventory_inventoryPb_inventoryPb_proto_rawDescOnce sync.Once
	file_modules_inventory_inventoryPb_inventoryPb_proto_rawDescData []byte
)

func file_modules_inventory_inventoryPb_inventoryPb_proto_rawDescGZIP() []byte {
	file_modules_inventory_inventoryPb_inventoryPb_proto_rawDescOnce.Do(func() {
		file_modules_inventory_inventoryPb_inventoryPb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_inventory_inventoryPb_inventoryPb_proto_rawDesc), len(file_modules_inventory_inventoryPb_inventoryPb_proto_rawDesc)))
	})
	return file_modules_inventory_inventoryPb_inventoryPb_proto_rawDescData
}

var file_modules_inventory_inventoryPb_inventoryPb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_inventory_inventoryPb_inventoryPb_proto_goTypes = []any{
	(*IsAvailableToSellReq)(nil), // 0: inventorypb.IsAvailableToSellReq
	(*IsAvailableToSellRes)(nil), // 1: inventorypb.IsAvailableToSellRes
}
var file_modules_inventory_inventoryPb_inventoryPb_proto_depIdxs = []int32{
	0, // 0: inventorypb.InventoryGrpcService.IsAvailableToSell:input_type -> inventorypb.IsAvailableToSellReq
	1, // 1: inventorypb.InventoryGrpcService.IsAvailableToSell:output_type -> inventorypb.IsAvailableToSellRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_inventory_inventoryPb_inventoryPb_proto_init() }
func file_modules_inventory_inventoryPb_inventoryPb_proto_init() {
	if File_modules_inventory_inventoryPb_inventoryPb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_inventory_inventoryPb_inventoryPb_proto_rawDesc), len(file_modules_inventory_inventoryPb_inventoryPb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_inventory_inventoryPb_inventoryPb_proto_goTypes,
		DependencyIndexes: file_modules_inventory_inventoryPb_inventoryPb_proto_depIdxs,
		MessageInfos:      file_modules_inventory_inventoryPb_inventoryPb_proto_msgTypes,
	}.Build()
	File_modules_inventory_inventoryPb_inventoryPb_proto = out.File
	file_modules_inventory_inventoryPb_inventoryPb_proto_goTypes = nil
	file_modules_inventory_inventoryPb_inventoryPb_proto_depIdxs = nil
}
